-- // create_user_group_table
CREATE TABLE Q_USER_GROUP (
    ID          NUMERIC(20, 0) NOT NULL,
    GROUP_ID    NUMERIC(20, 0) NOT NULL,
    PARTICIPANT NUMBER(20,0) NOT NULL,
    THEME       VARCHAR(20),
    MUTED       NUMBER(1,0) DEFAULT 0,
    CREATED_BY NUMERIC(20, 0),
    UPDATED_BY NUMERIC(20, 0),
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE
)/execute/

ALTER TABLE Q_USER_GROUP
    ADD CONSTRAINT Q_USER_GROUP_PK
        PRIMARY KEY (ID)
/execute/

-- //@UNDO
DROP TABLE Q_USER_GROUP
/execute/


