-- // create_user_friend_constraints
ALTER TABLE Q_USER_FRIEND
    ADD CONSTRAINT Q_USER_FRIEND_USER_FK
        FOREIGN KEY (USER_ID)
            REFERENCES Q_USER(ACCOUNT_ID)
/execute/

ALTER TABLE Q_USER_FRIEND
    ADD CONSTRAINT Q_USER_FRIEND_FRIEND_FK
        FOREIGN KEY (FRIEND_ID)
            REFERENCES Q_USER(ACCOUNT_ID)
/execute/

-- //@UNDO
-- SQL to undo the change goes here.
ALTER TABLE Q_USER_FRIEND DROP CONSTRAINT Q_USER_FRIEND_USER_FK
/execute/
 ALTER TABLE Q_USER_FRIEND DROP CONSTRAINT Q_USER_FRIEND_FRIEND_FK
/execute/