-- // create_user_friend_table
CREATE TABLE Q_USER_FRIEND (
    USER_ID NUMERIC(20, 0) NOT NULL,
    FRIEND_ID NUMERIC(20, 0) NOT NULL,
    CREATED_BY NUMERIC(20, 0),
    UPDATED_BY NUMERIC(20, 0),
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE
)
/execute/

ALTER TABLE Q_USER_FRIEND
    ADD CONSTRAINT Q_USER_FRIEND_PK
        PRIMARY KEY (USER_ID, FRIEND_ID)
/execute/

-- //@UNDO
DROP TABLE Q_USER_FRIEND
/execute/


