-- // add_more_cars_questions
-- 300 more Cars questions, on top of 20261004100000_add_cars_questions. New terms go into the
-- glossary types that migration created (so every Cars question draws its wrong options from the
-- one bigger pool), plus two new types: car technology and body styles. A question may reuse a
-- term from the first migration as its answer.
--
-- New terms are keyed CARS_ (the first migration's are CAR_), and the new questions carry their
-- glossary type's name as TOPIC; that is how the undo tells them apart from the first 100.
--
-- EXCLUDE_TYPE 32 = every quiz type except MAP_CHOICE.
DECLARE
    v_type NUMBER;
    v_topic VARCHAR2(100);
    v_cat NUMBER;

    PROCEDURE add_type(p_name VARCHAR2) IS
    BEGIN
        v_type := GLOSSARY_TYPE_SEQ.NEXTVAL;
        v_topic := p_name;
        INSERT INTO Q_GLOSSARY_TYPE (ID, NAME, IS_ACTIVE, CREATED_BY, CREATED_DATE)
        VALUES (v_type, p_name, 1, 1, SYSDATE);
    END;

    -- A type the first Cars migration created.
    PROCEDURE use_type(p_name VARCHAR2) IS
    BEGIN
        v_topic := p_name;
        SELECT DISTINCT t.ID INTO v_type FROM Q_GLOSSARY_TYPE t JOIN Q_GLOSSARY g ON g.TYPE_ID = t.ID
        WHERE t.NAME = p_name AND g.CAT_ID = v_cat AND g.KEY LIKE 'CAR\_%' ESCAPE '\';
    END;

    PROCEDURE term(p_key VARCHAR2, p_value VARCHAR2) IS
    BEGIN
        INSERT INTO Q_GLOSSARY (TERM_ID, KEY, VALUE, CAT_ID, TYPE_ID, IS_ACTIVE, CREATED_BY, CREATED_DATE)
        VALUES (GLOSSARIES_SEQ.NEXTVAL, p_key, p_value, v_cat, v_type, 1, 1, SYSDATE);
    END;

    -- A question whose one correct answer is the term with this key.
    PROCEDURE ask(p_content VARCHAR2, p_key VARCHAR2) IS
        v_question NUMBER := QUESTIONS_SEQ.NEXTVAL;
        v_term NUMBER; v_value VARCHAR2(100);
    BEGIN
        SELECT TERM_ID, VALUE INTO v_term, v_value FROM Q_GLOSSARY WHERE KEY = p_key AND CAT_ID = v_cat AND TYPE_ID = v_type;
        INSERT INTO Q_QUESTION (QUESTION_ID, ACCOUNT_ID, TYPE, CAT_ID, IS_ACTIVE, COMPLEXITY_LEVEL, PRIORITY, CONTENT, TOPIC, ATTRIBUTES, EXCLUDE_TYPE, CREATED_BY, CREATED_DATE)
        VALUES (v_question, 1, 'CREATED', v_cat, 1, 1, 1, p_content, v_topic, 'ANSWER_BY_VALUE', 32, 1, SYSDATE);
        INSERT INTO Q_ANSWER (ANS_ID, QUESTION_ID, CONTENT, TERM_ID, CREATED_BY, CREATED_DATE)
        VALUES (ANSWERS_SEQ.NEXTVAL, v_question, v_value, v_term, 1, SYSDATE);
    END;
BEGIN
    SELECT CAT_ID INTO v_cat FROM Q_CATEGORY WHERE NAME = 'Cars';

    use_type('Car brands');
    term('CARS_BRAND_PAGANI', 'Pagani');
    term('CARS_BRAND_RIMAC', 'Rimac');
    term('CARS_BRAND_CADILLAC', 'Cadillac');
    term('CARS_BRAND_BUICK', 'Buick');
    term('CARS_BRAND_CHRYSLER', 'Chrysler');
    term('CARS_BRAND_LINCOLN', 'Lincoln');
    term('CARS_BRAND_ACURA', 'Acura');
    term('CARS_BRAND_INFINITI', 'Infiniti');
    term('CARS_BRAND_MITSUBISHI', 'Mitsubishi');
    term('CARS_BRAND_SUZUKI', 'Suzuki');
    term('CARS_BRAND_OPEL', 'Opel');
    term('CARS_BRAND_VAUXHALL', 'Vauxhall');
    term('CARS_BRAND_SEAT', 'SEAT');
    term('CARS_BRAND_CUPRA', 'Cupra');
    term('CARS_BRAND_SMART', 'Smart');
    term('CARS_BRAND_POLESTAR', 'Polestar');
    term('CARS_BRAND_GENESIS', 'Genesis');
    term('CARS_BRAND_BYD', 'BYD');
    term('CARS_BRAND_TATA', 'Tata');
    term('CARS_BRAND_MAHINDRA', 'Mahindra');
    term('CARS_BRAND_LANCIA', 'Lancia');
    term('CARS_BRAND_ABARTH', 'Abarth');
    term('CARS_BRAND_ALPINE', 'Alpine');
    term('CARS_BRAND_SAAB', 'Saab');
    term('CARS_BRAND_PONTIAC', 'Pontiac');
    term('CARS_BRAND_HUMMER', 'Hummer');
    term('CARS_BRAND_LUCID', 'Lucid');
    term('CARS_BRAND_RIVIAN', 'Rivian');
    term('CARS_BRAND_MAYBACH', 'Maybach');
    term('CARS_BRAND_TRABANT', 'Trabant');
    term('CARS_BRAND_GEELY', 'Geely');
    ask('Which Italian hypercar maker builds the Zonda and the Huayra?', 'CARS_BRAND_PAGANI');
    ask('Which Croatian company builds the Nevera electric hypercar?', 'CARS_BRAND_RIMAC');
    ask('Which General Motors luxury brand builds the Escalade?', 'CARS_BRAND_CADILLAC');
    ask('Which Ford luxury brand builds the Navigator?', 'CARS_BRAND_LINCOLN');
    ask('Which brand is Honda''s luxury division in North America?', 'CARS_BRAND_ACURA');
    ask('Which brand is Nissan''s luxury division?', 'CARS_BRAND_INFINITI');
    ask('Which Japanese carmaker builds the Lancer Evolution and the Pajero?', 'CARS_BRAND_MITSUBISHI');
    ask('Which Japanese carmaker builds the Swift and the Jimny?', 'CARS_BRAND_SUZUKI');
    ask('Which German carmaker builds the Corsa and the Astra?', 'CARS_BRAND_OPEL');
    ask('Which British brand sells Opel cars under its own badge?', 'CARS_BRAND_VAUXHALL');
    ask('Which Spanish carmaker builds the Ibiza and the Leon?', 'CARS_BRAND_SEAT');
    ask('Which performance brand was spun off from SEAT in 2018?', 'CARS_BRAND_CUPRA');
    ask('Which brand builds the tiny two-seat Fortwo city car?', 'CARS_BRAND_SMART');
    ask('Which Swedish electric car brand started out as Volvo''s performance division?', 'CARS_BRAND_POLESTAR');
    ask('Which brand is Hyundai''s luxury division?', 'CARS_BRAND_GENESIS');
    ask('Which Chinese carmaker''s name stands for "Build Your Dreams"?', 'CARS_BRAND_BYD');
    ask('Which Indian company owns Jaguar Land Rover?', 'CARS_BRAND_TATA');
    ask('Which Indian carmaker builds the Scorpio and the Thar SUVs?', 'CARS_BRAND_MAHINDRA');
    ask('Which Italian carmaker dominated the World Rally Championship with the Delta Integrale?', 'CARS_BRAND_LANCIA');
    ask('Which brand with a scorpion logo builds sporty versions of Fiats?', 'CARS_BRAND_ABARTH');
    ask('Which French carmaker builds the A110 sports car?', 'CARS_BRAND_ALPINE');
    ask('Which Swedish carmaker, born from an aircraft company, built the 900 and the 9-3?', 'CARS_BRAND_SAAB');
    ask('Which defunct General Motors brand built the Firebird and the GTO?', 'CARS_BRAND_PONTIAC');
    ask('Which brand took its name from the military Humvee?', 'CARS_BRAND_HUMMER');
    ask('Which American electric carmaker builds the Air sedan?', 'CARS_BRAND_LUCID');
    ask('Which American electric carmaker builds the R1T pickup?', 'CARS_BRAND_RIVIAN');
    ask('Which name does Mercedes-Benz use for its ultra-luxury models?', 'CARS_BRAND_MAYBACH');
    ask('Which East German car had a body made of Duroplast?', 'CARS_BRAND_TRABANT');
    ask('Which Chinese company owns Volvo Cars?', 'CARS_BRAND_GEELY');
    ask('Which American brand builds the 300 sedan and the Pacifica minivan?', 'CARS_BRAND_CHRYSLER');
    ask('Which General Motors brand builds the Enclave and is especially popular in China?', 'CARS_BRAND_BUICK');
    ask('Which carmaker builds the Outlander SUV?', 'CARS_BRAND_MITSUBISHI');
    ask('Which carmaker builds the Cayenne SUV?', 'CAR_BRAND_PORSCHE');
    ask('Which carmaker builds the Taycan electric sports car?', 'CAR_BRAND_PORSCHE');
    ask('Which carmaker''s M division builds performance cars like the M3?', 'CAR_BRAND_BMW');
    ask('Which carmaker''s AMG division builds its high-performance models?', 'CAR_BRAND_MERCEDES');
    ask('Which carmaker builds the R8 supercar?', 'CAR_BRAND_AUDI');
    ask('Which carmaker builds the Supra sports car?', 'CAR_BRAND_TOYOTA');
    ask('Which carmaker built the NSX supercar?', 'CAR_BRAND_HONDA');
    ask('Which carmaker builds the Leaf electric car?', 'CAR_BRAND_NISSAN');
    ask('Which carmaker builds the F-150 pickup?', 'CAR_BRAND_FORD');
    ask('Which carmaker builds the Camaro?', 'CAR_BRAND_CHEVROLET');
    ask('Which carmaker builds the Cybertruck?', 'CAR_BRAND_TESLA');
    ask('Which carmaker builds the XC90 SUV?', 'CAR_BRAND_VOLVO');
    ask('Which carmaker builds the Phantom and the Cullinan?', 'CAR_BRAND_ROLLS_ROYCE');
    ask('Which carmaker built the EB110 supercar in the 1990s?', 'CAR_BRAND_BUGATTI');
    ask('Which carmaker builds the Vantage and the DBS?', 'CAR_BRAND_ASTON_MARTIN');
    ask('Which carmaker built the E-Type, called "the most beautiful car ever made" by Enzo Ferrari?', 'CAR_BRAND_JAGUAR');
    ask('Which carmaker builds the WRX and the Forester?', 'CAR_BRAND_SUBARU');
    ask('Which carmaker put the Wankel rotary engine in the RX-7?', 'CAR_BRAND_MAZDA');
    ask('Which carmaker builds the 208 and the 3008?', 'CAR_BRAND_PEUGEOT');
    ask('Which carmaker builds the Megane and the Zoe?', 'CAR_BRAND_RENAULT');
    ask('Which carmaker built the DS, nicknamed "the Goddess"?', 'CAR_BRAND_CITROEN');
    ask('Which carmaker builds the Ioniq 5 electric car?', 'CAR_BRAND_HYUNDAI');
    ask('Which carmaker builds the EV6 and the Stinger?', 'CAR_BRAND_KIA');
    ask('Which carmaker builds the Octavia and the Superb?', 'CAR_BRAND_SKODA');
    ask('Which carmaker builds the Duster and the Sandero?', 'CAR_BRAND_DACIA');
    ask('Which carmaker built the Viper sports car?', 'CAR_BRAND_DODGE');
    ask('Which carmaker builds the Grand Cherokee?', 'CAR_BRAND_JEEP');
    ask('Which carmaker builds the Discovery off-roader?', 'CAR_BRAND_LAND_ROVER');
    ask('Which carmaker built the LFA supercar?', 'CAR_BRAND_LEXUS');
    ask('Which carmaker builds the Stelvio SUV and the Giulia?', 'CAR_BRAND_ALFA_ROMEO');
    ask('Which carmaker builds the 720S and built the P1?', 'CAR_BRAND_MCLAREN');
    ask('Which carmaker builds the Bentayga SUV?', 'CAR_BRAND_BENTLEY');
    ask('Which carmaker builds the MC20 and the Ghibli?', 'CAR_BRAND_MASERATI');
    ask('Which carmaker builds the Countryman?', 'CAR_BRAND_MINI');
    ask('Which carmaker builds the Regera hypercar?', 'CAR_BRAND_KOENIGSEGG');
    ask('Which carmaker built the Esprit that turned into a submarine in The Spy Who Loved Me?', 'CAR_BRAND_LOTUS');
    ask('Which carmaker builds the Panda city car?', 'CAR_BRAND_FIAT');
    ask('Which carmaker builds the Huracan and the Urus?', 'CAR_BRAND_LAMBORGHINI');
    ask('Which carmaker builds the SF90 and the Roma?', 'CAR_BRAND_FERRARI');
    ask('Which carmaker''s name means "people''s car" in German?', 'CAR_BRAND_VOLKSWAGEN');

    use_type('Car countries');
    term('CARS_COUNTRY_SPAIN', 'Spain');
    term('CARS_COUNTRY_CROATIA', 'Croatia');
    term('CARS_COUNTRY_NETHERLANDS', 'Netherlands');
    term('CARS_COUNTRY_MALAYSIA', 'Malaysia');
    term('CARS_COUNTRY_AUSTRALIA', 'Australia');
    term('CARS_COUNTRY_RUSSIA', 'Russia');
    term('CARS_COUNTRY_VIETNAM', 'Vietnam');
    term('CARS_COUNTRY_TURKEY', 'Turkey');
    term('CARS_COUNTRY_BRAZIL', 'Brazil');
    term('CARS_COUNTRY_BELGIUM', 'Belgium');
    term('CARS_COUNTRY_SWITZERLAND', 'Switzerland');
    ask('Which country does SEAT come from?', 'CARS_COUNTRY_SPAIN');
    ask('Which country does Rimac come from?', 'CARS_COUNTRY_CROATIA');
    ask('Which country does Spyker come from?', 'CARS_COUNTRY_NETHERLANDS');
    ask('Which country does Proton come from?', 'CARS_COUNTRY_MALAYSIA');
    ask('Which country did Holden come from?', 'CARS_COUNTRY_AUSTRALIA');
    ask('Which country does Lada come from?', 'CARS_COUNTRY_RUSSIA');
    ask('Which country does VinFast come from?', 'CARS_COUNTRY_VIETNAM');
    ask('Which country does Togg come from?', 'CARS_COUNTRY_TURKEY');
    ask('Which country does Koenigsegg come from?', 'CAR_COUNTRY_SWEDEN');
    ask('Which country does Pagani come from?', 'CAR_COUNTRY_ITALY');
    ask('Which country does Bentley come from?', 'CAR_COUNTRY_UK');
    ask('Which country does Subaru come from?', 'CAR_COUNTRY_JAPAN');
    ask('Which country does Cadillac come from?', 'CAR_COUNTRY_USA');
    ask('Which country does Alpine come from?', 'CAR_COUNTRY_FRANCE');
    ask('Which country does Kia come from?', 'CAR_COUNTRY_SOUTH_KOREA');
    ask('Which country does Mahindra come from?', 'CAR_COUNTRY_INDIA');
    ask('Which country does Geely come from?', 'CAR_COUNTRY_CHINA');
    ask('Which country does Opel come from?', 'CAR_COUNTRY_GERMANY');
    ask('Which country did Saab come from?', 'CAR_COUNTRY_SWEDEN');
    ask('Which country does Tatra come from?', 'CAR_COUNTRY_CZECHIA');
    ask('In which country is the Nurburgring?', 'CAR_COUNTRY_GERMANY');
    ask('In which country is the 24 Hours of Le Mans held?', 'CAR_COUNTRY_FRANCE');
    ask('In which country is the Suzuka circuit?', 'CAR_COUNTRY_JAPAN');
    ask('In which country is the Interlagos circuit?', 'CARS_COUNTRY_BRAZIL');
    ask('In which country is the Spa-Francorchamps circuit?', 'CARS_COUNTRY_BELGIUM');
    ask('In which country is the Silverstone circuit?', 'CAR_COUNTRY_UK');
    ask('In which country is Detroit, nicknamed "Motor City"?', 'CAR_COUNTRY_USA');
    ask('In which country is Stuttgart, home of Porsche and Mercedes-Benz?', 'CAR_COUNTRY_GERMANY');
    ask('In which country is Maranello, home of Ferrari?', 'CAR_COUNTRY_ITALY');
    ask('Which country uses the international vehicle registration code "CH"?', 'CARS_COUNTRY_SWITZERLAND');
    ask('Which country uses the international vehicle registration code "E"?', 'CARS_COUNTRY_SPAIN');

    use_type('Car parts');
    term('CARS_PART_CAMSHAFT', 'Camshaft');
    term('CARS_PART_PISTON', 'Piston');
    term('CARS_PART_HEAD_GASKET', 'Head gasket');
    term('CARS_PART_WATER_PUMP', 'Water pump');
    term('CARS_PART_THERMOSTAT', 'Thermostat');
    term('CARS_PART_INTERCOOLER', 'Intercooler');
    term('CARS_PART_SUPERCHARGER', 'Supercharger');
    term('CARS_PART_TORQUE_CONVERTER', 'Torque converter');
    term('CARS_PART_DRIVE_SHAFT', 'Drive shaft');
    term('CARS_PART_CV_JOINT', 'CV joint');
    term('CARS_PART_ANTI_ROLL_BAR', 'Anti-roll bar');
    term('CARS_PART_MASTER_CYLINDER', 'Master cylinder');
    term('CARS_PART_BRAKE_PAD', 'Brake pad');
    term('CARS_PART_BRAKE_DISC', 'Brake disc');
    term('CARS_PART_AIR_FILTER', 'Air filter');
    term('CARS_PART_OIL_FILTER', 'Oil filter');
    term('CARS_PART_EXHAUST_MANIFOLD', 'Exhaust manifold');
    term('CARS_PART_INTAKE_MANIFOLD', 'Intake manifold');
    term('CARS_PART_FLYWHEEL', 'Flywheel');
    term('CARS_PART_DISTRIBUTOR', 'Distributor');
    term('CARS_PART_IGNITION_COIL', 'Ignition coil');
    term('CARS_PART_GLOW_PLUG', 'Glow plug');
    term('CARS_PART_OXYGEN_SENSOR', 'Oxygen sensor');
    term('CARS_PART_TACHOMETER', 'Tachometer');
    term('CARS_PART_ODOMETER', 'Odometer');
    term('CARS_PART_LEAF_SPRING', 'Leaf spring');
    term('CARS_PART_MACPHERSON', 'MacPherson strut');
    term('CARS_PART_TIE_ROD', 'Tie rod');
    term('CARS_PART_FUEL_PUMP', 'Fuel pump');
    term('CARS_PART_OIL_PUMP', 'Oil pump');
    term('CARS_PART_CYLINDER_HEAD', 'Cylinder head');
    ask('Which part opens and closes the engine''s valves?', 'CARS_PART_CAMSHAFT');
    ask('Which part moves up and down inside an engine cylinder?', 'CARS_PART_PISTON');
    ask('Which gasket seals the cylinder head to the engine block?', 'CARS_PART_HEAD_GASKET');
    ask('Which part circulates coolant through the engine?', 'CARS_PART_WATER_PUMP');
    ask('Which valve lets coolant reach the radiator only once the engine has warmed up?', 'CARS_PART_THERMOSTAT');
    ask('Which part cools the compressed air coming out of a turbocharger?', 'CARS_PART_INTERCOOLER');
    ask('Which compressor, driven by the engine itself, forces more air into the cylinders?', 'CARS_PART_SUPERCHARGER');
    ask('Which fluid coupling takes the place of the clutch in a traditional automatic gearbox?', 'CARS_PART_TORQUE_CONVERTER');
    ask('Which shaft carries power from the gearbox to the rear axle of a rear-wheel-drive car?', 'CARS_PART_DRIVE_SHAFT');
    ask('Which joint lets a front axle shaft keep delivering power while the wheels steer?', 'CARS_PART_CV_JOINT');
    ask('Which bar links the left and right suspension to reduce body roll in corners?', 'CARS_PART_ANTI_ROLL_BAR');
    ask('Which part turns the push on the brake pedal into hydraulic pressure?', 'CARS_PART_MASTER_CYLINDER');
    ask('Which friction part of a disc brake wears out and has to be replaced regularly?', 'CARS_PART_BRAKE_PAD');
    ask('Which part spins with the wheel and is squeezed by the caliper?', 'CARS_PART_BRAKE_DISC');
    ask('Which part stops dust and dirt from entering the engine with the air?', 'CARS_PART_AIR_FILTER');
    ask('Which part cleans the engine oil?', 'CARS_PART_OIL_FILTER');
    ask('Which part collects the exhaust gases from all cylinders into one pipe?', 'CARS_PART_EXHAUST_MANIFOLD');
    ask('Which part spreads the incoming air to each cylinder?', 'CARS_PART_INTAKE_MANIFOLD');
    ask('Which heavy disc smooths out engine rotation and meets the clutch?', 'CARS_PART_FLYWHEEL');
    ask('In older engines, which part sent the high voltage to each spark plug in turn?', 'CARS_PART_DISTRIBUTOR');
    ask('Which part turns the battery''s 12 volts into the thousands of volts a spark plug needs?', 'CARS_PART_IGNITION_COIL');
    ask('Which part heats the combustion chamber to help a diesel engine start in the cold?', 'CARS_PART_GLOW_PLUG');
    ask('Which sensor measures the oxygen in the exhaust to adjust the fuel mixture?', 'CARS_PART_OXYGEN_SENSOR');
    ask('Which gauge shows the engine speed in revolutions per minute?', 'CARS_PART_TACHOMETER');
    ask('Which gauge records the total distance a car has travelled?', 'CARS_PART_ODOMETER');
    ask('Which spring made of stacked steel strips is still used on many trucks?', 'CARS_PART_LEAF_SPRING');
    ask('Which front suspension design, named after a Ford engineer, combines the spring and damper in one unit?', 'CARS_PART_MACPHERSON');
    ask('Which rod connects the steering rack to the wheel?', 'CARS_PART_TIE_ROD');
    ask('Which pump delivers fuel from the tank to the engine?', 'CARS_PART_FUEL_PUMP');
    ask('Which pump keeps oil flowing through the engine?', 'CARS_PART_OIL_PUMP');
    ask('Which part, bolted on top of the engine block, holds the valves?', 'CARS_PART_CYLINDER_HEAD');
    ask('Which part of the cooling system has a pressure cap you should never open while it is hot?', 'CAR_PART_RADIATOR');
    ask('Which part holds the gears that change the ratio between the engine and the wheels?', 'CAR_PART_GEARBOX');
    ask('Which part causes the delay known as "lag" before the extra power arrives?', 'CAR_PART_TURBO');
    ask('Which exhaust part became required on new cars in the United States from the 1975 model year?', 'CAR_PART_CATALYTIC');

    use_type('Automotive people');
    term('CARS_PERSON_BUGATTI', 'Ettore Bugatti');
    term('CARS_PERSON_ROYCE', 'Henry Royce');
    term('CARS_PERSON_DELOREAN', 'John DeLorean');
    term('CARS_PERSON_CHAPMAN', 'Colin Chapman');
    term('CARS_PERSON_MCLAREN', 'Bruce McLaren');
    term('CARS_PERSON_PAGANI', 'Horacio Pagani');
    term('CARS_PERSON_KOENIGSEGG', 'Christian von Koenigsegg');
    term('CARS_PERSON_RIMAC', 'Mate Rimac');
    term('CARS_PERSON_GIUGIARO', 'Giorgetto Giugiaro');
    term('CARS_PERSON_GANDINI', 'Marcello Gandini');
    term('CARS_PERSON_ISSIGONIS', 'Alec Issigonis');
    term('CARS_PERSON_SHELBY', 'Carroll Shelby');
    term('CARS_PERSON_FANGIO', 'Juan Manuel Fangio');
    term('CARS_PERSON_LAUDA', 'Niki Lauda');
    term('CARS_PERSON_PROST', 'Alain Prost');
    term('CARS_PERSON_VETTEL', 'Sebastian Vettel');
    term('CARS_PERSON_VERSTAPPEN', 'Max Verstappen');
    term('CARS_PERSON_ALONSO', 'Fernando Alonso');
    term('CARS_PERSON_STEWART', 'Jackie Stewart');
    term('CARS_PERSON_LOEB', 'Sebastien Loeb');
    term('CARS_PERSON_MCRAE', 'Colin McRae');
    term('CARS_PERSON_BERTHA_BENZ', 'Bertha Benz');
    term('CARS_PERSON_LYONS', 'William Lyons');
    term('CARS_PERSON_FERRY_PORSCHE', 'Ferry Porsche');
    term('CARS_PERSON_OLDS', 'Ransom Olds');
    term('CARS_PERSON_CHRYSLER', 'Walter Chrysler');
    term('CARS_PERSON_PININFARINA', 'Battista Pininfarina');
    term('CARS_PERSON_HUNT', 'James Hunt');
    ask('Who founded the French carmaker that built the Type 35 racer?', 'CARS_PERSON_BUGATTI');
    ask('Which engineer teamed up with Charles Rolls in 1904?', 'CARS_PERSON_ROYCE');
    ask('Which former General Motors executive founded the company behind the gull-winged DMC-12?', 'CARS_PERSON_DELOREAN');
    ask('Who founded Lotus and preached "simplify, then add lightness"?', 'CARS_PERSON_CHAPMAN');
    ask('Which New Zealand driver founded a racing team in 1963 that still races in Formula 1?', 'CARS_PERSON_MCLAREN');
    ask('Which Argentine-born designer founded a hypercar company near Modena?', 'CARS_PERSON_PAGANI');
    ask('Who founded a Swedish hypercar company in 1994 at the age of 22?', 'CARS_PERSON_KOENIGSEGG');
    ask('Which Croatian entrepreneur started building electric cars in his garage and later took over Bugatti?', 'CARS_PERSON_RIMAC');
    ask('Which Italian designer drew the first Volkswagen Golf and the DeLorean DMC-12?', 'CARS_PERSON_GIUGIARO');
    ask('Which designer at Bertone drew the Lamborghini Miura and the Countach?', 'CARS_PERSON_GANDINI');
    ask('Who designed the original Mini of 1959?', 'CARS_PERSON_ISSIGONIS');
    ask('Which American racer created the AC Cobra and tuned Ford Mustangs?', 'CARS_PERSON_SHELBY');
    ask('Which Argentine won five Formula 1 world titles in the 1950s?', 'CARS_PERSON_FANGIO');
    ask('Which Austrian returned to racing weeks after a fiery crash at the Nurburgring in 1976?', 'CARS_PERSON_LAUDA');
    ask('Which Frenchman, nicknamed "The Professor", won four Formula 1 titles?', 'CARS_PERSON_PROST');
    ask('Which German won four Formula 1 titles in a row with Red Bull from 2010 to 2013?', 'CARS_PERSON_VETTEL');
    ask('Which Dutch driver won his first Formula 1 title at Abu Dhabi in 2021?', 'CARS_PERSON_VERSTAPPEN');
    ask('Which Spaniard won the Formula 1 titles of 2005 and 2006 with Renault?', 'CARS_PERSON_ALONSO');
    ask('Which Scottish three-time Formula 1 champion, "the Flying Scot", campaigned for safety in racing?', 'CARS_PERSON_STEWART');
    ask('Which Frenchman won nine World Rally titles in a row from 2004 to 2012?', 'CARS_PERSON_LOEB');
    ask('Which Scottish rally driver won the 1995 world title with Subaru?', 'CARS_PERSON_MCRAE');
    ask('Who made the first long-distance car journey in 1888, in her husband''s Motorwagen?', 'CARS_PERSON_BERTHA_BENZ');
    ask('Who co-founded the Swallow Sidecar Company, which later became Jaguar?', 'CARS_PERSON_LYONS');
    ask('Which son of Ferdinand Porsche launched the first Porsche-badged car, the 356?', 'CARS_PERSON_FERRY_PORSCHE');
    ask('Who founded Oldsmobile and built the Curved Dash, the first mass-produced car?', 'CARS_PERSON_OLDS');
    ask('Which carmaker''s founder gave his name to an Art Deco skyscraper in New York?', 'CARS_PERSON_CHRYSLER');
    ask('Which Italian coachbuilder founded the design house that styled Ferraris for decades?', 'CARS_PERSON_PININFARINA');
    ask('Which British driver beat Niki Lauda to the 1976 Formula 1 title, as told in the film Rush?', 'CARS_PERSON_HUNT');
    ask('Who paid his workers $5 a day in 1914 so they could afford the cars they built?', 'CAR_PERSON_FORD');
    ask('Which entrepreneur has led Tesla as CEO since 2008?', 'CAR_PERSON_MUSK');
    ask('Whose surname, joined with Daimler''s, appears in the name Mercedes-Benz?', 'CAR_PERSON_BENZ');
    ask('Who was nicknamed "Il Commendatore"?', 'CAR_PERSON_ENZO_FERRARI');
    ask('Whose engine ran on peanut oil at the 1900 Paris World Fair?', 'CAR_PERSON_DIESEL');
    ask('Which driver won his first Formula 1 title with McLaren in 1988?', 'CAR_PERSON_SENNA');
    ask('Which driver holds the record for the most Formula 1 race wins?', 'CAR_PERSON_HAMILTON');
    ask('Which driver won his first Formula 1 title with Benetton in 1994?', 'CAR_PERSON_SCHUMACHER');
    ask('Who made piston rings before founding his own motorcycle and car company?', 'CAR_PERSON_HONDA');

    use_type('Car models');
    term('CARS_MODEL_MIURA', 'Lamborghini Miura');
    term('CARS_MODEL_E_TYPE', 'Jaguar E-Type');
    term('CARS_MODEL_300SL', 'Mercedes-Benz 300 SL');
    term('CARS_MODEL_DB5', 'Aston Martin DB5');
    term('CARS_MODEL_GT40', 'Ford GT40');
    term('CARS_MODEL_QUATTRO', 'Audi Quattro');
    term('CARS_MODEL_SUPRA', 'Toyota Supra');
    term('CARS_MODEL_240Z', 'Datsun 240Z');
    term('CARS_MODEL_MX5', 'Mazda MX-5');
    term('CARS_MODEL_FIAT_500', 'Fiat 500');
    term('CARS_MODEL_CLIO', 'Renault Clio');
    term('CARS_MODEL_NSX', 'Honda NSX');
    term('CARS_MODEL_EVO', 'Mitsubishi Lancer Evolution');
    term('CARS_MODEL_IMPREZA', 'Subaru Impreza');
    term('CARS_MODEL_DELTA', 'Lancia Delta');
    term('CARS_MODEL_LR_SERIES_1', 'Land Rover Series I');
    term('CARS_MODEL_WILLYS', 'Willys MB');
    term('CARS_MODEL_VW_BUS', 'Volkswagen Type 2');
    term('CARS_MODEL_F150', 'Ford F-150');
    term('CARS_MODEL_CHARGER', 'Dodge Charger');
    term('CARS_MODEL_TRANS_AM', 'Pontiac Firebird Trans Am');
    term('CARS_MODEL_MODEL_3', 'Tesla Model 3');
    term('CARS_MODEL_ROADSTER', 'Tesla Roadster');
    term('CARS_MODEL_LEAF', 'Nissan Leaf');
    term('CARS_MODEL_MCLAREN_F1', 'McLaren F1');
    term('CARS_MODEL_CHIRON', 'Bugatti Chiron');
    term('CARS_MODEL_LAFERRARI', 'LaFerrari');
    term('CARS_MODEL_918', 'Porsche 918 Spyder');
    term('CARS_MODEL_CAYENNE', 'Porsche Cayenne');
    term('CARS_MODEL_VOLVO_240', 'Volvo 240');
    term('CARS_MODEL_DS', 'Citroen DS');
    term('CARS_MODEL_205', 'Peugeot 205');
    term('CARS_MODEL_TRABANT_601', 'Trabant 601');
    term('CARS_MODEL_ZHIGULI', 'Lada Zhiguli');
    term('CARS_MODEL_HILUX', 'Toyota Hilux');
    term('CARS_MODEL_H1', 'Hummer H1');
    term('CARS_MODEL_BOLT', 'Chevrolet Bolt');
    term('CARS_MODEL_M3', 'BMW M3');
    term('CARS_MODEL_ISETTA', 'BMW Isetta');
    term('CARS_MODEL_G_CLASS', 'Mercedes-Benz G-Class');
    term('CARS_MODEL_HURACAN', 'Lamborghini Huracan');
    term('CARS_MODEL_CULLINAN', 'Rolls-Royce Cullinan');
    term('CARS_MODEL_MIRAI', 'Toyota Mirai');
    term('CARS_MODEL_CIVIC', 'Honda Civic');
    term('CARS_MODEL_COBRA', 'AC Cobra');
    term('CARS_MODEL_NANO', 'Tata Nano');
    term('CARS_MODEL_RAV4', 'Toyota RAV4');
    ask('Which Lamborghini, launched in 1966, is often called the first supercar?', 'CARS_MODEL_MIURA');
    ask('Which British sports car was unveiled at the 1961 Geneva Motor Show?', 'CARS_MODEL_E_TYPE');
    ask('Which Mercedes of 1954 had "gullwing" doors?', 'CARS_MODEL_300SL');
    ask('Which car did James Bond drive in Goldfinger?', 'CARS_MODEL_DB5');
    ask('Which car won Le Mans four years in a row from 1966 to 1969?', 'CARS_MODEL_GT40');
    ask('Which car brought four-wheel drive to rallying in 1980?', 'CARS_MODEL_QUATTRO');
    ask('Which Japanese sports car did Brian O''Conner drive in the first "Fast and Furious" film?', 'CARS_MODEL_SUPRA');
    ask('Which Japanese sports car of 1969 was sold as the Fairlady Z at home?', 'CARS_MODEL_240Z');
    ask('Which roadster is the best-selling two-seat sports car in history?', 'CARS_MODEL_MX5');
    ask('Which Italian city car of 1957 was brought back in a modern form in 2007?', 'CARS_MODEL_FIAT_500');
    ask('Which French supermini, launched in 1990, was European Car of the Year twice?', 'CARS_MODEL_CLIO');
    ask('Which Japanese supercar was fine-tuned with the help of Ayrton Senna?', 'CARS_MODEL_NSX');
    ask('Which rally-bred Japanese sedan is nicknamed the "Evo"?', 'CARS_MODEL_EVO');
    ask('Which car did Colin McRae drive to his 1995 World Rally title?', 'CARS_MODEL_IMPREZA');
    ask('Which car won six World Rally manufacturers'' titles in a row from 1987 to 1992?', 'CARS_MODEL_DELTA');
    ask('Which British off-roader was launched at the 1948 Amsterdam Motor Show?', 'CARS_MODEL_LR_SERIES_1');
    ask('Which jeep was the US Army''s light utility vehicle in World War II?', 'CARS_MODEL_WILLYS');
    ask('Which van became a symbol of the 1960s hippie movement?', 'CARS_MODEL_VW_BUS');
    ask('Which pickup has been the best-selling vehicle in the United States for decades?', 'CARS_MODEL_F150');
    ask('Which muscle car was the "General Lee" in The Dukes of Hazzard?', 'CARS_MODEL_CHARGER');
    ask('Which car played KITT in the TV series Knight Rider?', 'CARS_MODEL_TRANS_AM');
    ask('Which car played "Eleanor" in the 2000 film Gone in 60 Seconds?', 'CAR_MODEL_MUSTANG');
    ask('Which car, launched in 2017, was Tesla''s first mass-market model?', 'CARS_MODEL_MODEL_3');
    ask('Which car was launched into space on a Falcon Heavy rocket in 2018?', 'CARS_MODEL_ROADSTER');
    ask('Which electric car was the world''s best-selling EV in the early 2010s?', 'CARS_MODEL_LEAF');
    ask('Which car with a central driving seat set a production car speed record in 1998?', 'CARS_MODEL_MCLAREN_F1');
    ask('Which hypercar, launched in 2016, has an 8.0-litre W16 engine with 1,500 horsepower?', 'CARS_MODEL_CHIRON');
    ask('Which Ferrari hybrid hypercar of 2013 is named after the company itself?', 'CARS_MODEL_LAFERRARI');
    ask('Which hybrid hypercar did Porsche launch in 2013?', 'CARS_MODEL_918');
    ask('Which car, launched in 2002, was Porsche''s first SUV?', 'CARS_MODEL_CAYENNE');
    ask('Which boxy Swedish car, built from 1974 to 1993, became an icon of safety?', 'CARS_MODEL_VOLVO_240');
    ask('Which French car of 1955 had hydropneumatic suspension and was nicknamed "the Goddess"?', 'CARS_MODEL_DS');
    ask('Which French hatchback, whose GTI version arrived in 1984, is a 1980s hot hatch icon?', 'CARS_MODEL_205');
    ask('Which East German car was built almost unchanged from 1964 to 1990?', 'CARS_MODEL_TRABANT_601');
    ask('Which Soviet car was based on the Fiat 124?', 'CARS_MODEL_ZHIGULI');
    ask('Which pickup did Top Gear famously fail to destroy?', 'CARS_MODEL_HILUX');
    ask('Which civilian off-roader was derived from the military Humvee?', 'CARS_MODEL_H1');
    ask('Which American electric hatchback, launched in 2016, had a range of 238 miles?', 'CARS_MODEL_BOLT');
    ask('Which sports sedan, first built in 1986 for touring car racing, wears the letter M?', 'CARS_MODEL_M3');
    ask('Which bubble car with a front-opening door was built under licence by BMW?', 'CARS_MODEL_ISETTA');
    ask('Which off-roader, first built in 1979, began as a military vehicle for Mercedes-Benz?', 'CARS_MODEL_G_CLASS');
    ask('Which V10 Lamborghini replaced the Gallardo in 2014?', 'CARS_MODEL_HURACAN');
    ask('Which car, launched in 2018, is Rolls-Royce''s first SUV?', 'CARS_MODEL_CULLINAN');
    ask('Which car, launched in 2014, was one of the first mass-produced hydrogen fuel cell cars?', 'CARS_MODEL_MIRAI');
    ask('Which Japanese hatchback is famous for its Type R versions?', 'CARS_MODEL_CIVIC');
    ask('Which roadster combined a British AC Ace body with a Ford V8?', 'CARS_MODEL_COBRA');
    ask('Which Indian city car, launched in 2008, was marketed as the world''s cheapest car?', 'CARS_MODEL_NANO');
    ask('Which crossover, launched in 1994, helped create the compact SUV class?', 'CARS_MODEL_RAV4');
    ask('Which car, built from 1938 to 2003, is the best-selling car built on a single platform?', 'CAR_MODEL_BEETLE');

    use_type('Motorsport');
    term('CARS_RACE_FORMULA_1', 'Formula 1');
    term('CARS_RACE_FORMULA_E', 'Formula E');
    term('CARS_RACE_NASCAR', 'NASCAR');
    term('CARS_RACE_DAYTONA_500', 'Daytona 500');
    term('CARS_RACE_PIKES_PEAK', 'Pikes Peak Hill Climb');
    term('CARS_RACE_SUZUKA', 'Suzuka');
    term('CARS_RACE_INTERLAGOS', 'Interlagos');
    term('CARS_RACE_IMOLA', 'Imola');
    term('CARS_RACE_BATHURST', 'Mount Panorama');
    term('CARS_RACE_GOODWOOD', 'Goodwood');
    term('CARS_RACE_LAGUNA_SECA', 'Laguna Seca');
    term('CARS_RACE_SEBRING', '12 Hours of Sebring');
    term('CARS_RACE_MONTE_CARLO_RALLY', 'Monte Carlo Rally');
    term('CARS_RACE_SINGAPORE', 'Singapore Grand Prix');
    term('CARS_RACE_BROOKLANDS', 'Brooklands');
    term('CARS_RACE_TARGA_FLORIO', 'Targa Florio');
    term('CARS_RACE_MILLE_MIGLIA', 'Mille Miglia');
    term('CARS_RACE_COTA', 'Circuit of the Americas');
    term('CARS_RACE_WRC', 'World Rally Championship');
    term('CARS_RACE_INDYCAR', 'IndyCar');
    term('CARS_RACE_DTM', 'DTM');
    term('CARS_RACE_PANAMERICANA', 'Carrera Panamericana');
    term('CARS_RACE_HUNGARORING', 'Hungaroring');
    ask('Which championship is raced with single-seater electric cars?', 'CARS_RACE_FORMULA_E');
    ask('Which American stock car series runs the Daytona 500?', 'CARS_RACE_NASCAR');
    ask('Which race is known as "The Great American Race"?', 'CARS_RACE_DAYTONA_500');
    ask('Which hill climb in Colorado finishes at about 4,300 metres above sea level?', 'CARS_RACE_PIKES_PEAK');
    ask('Which Japanese circuit has a figure-of-eight layout?', 'CARS_RACE_SUZUKA');
    ask('Which circuit in Sao Paulo hosts the Brazilian Grand Prix?', 'CARS_RACE_INTERLAGOS');
    ask('At which Italian circuit did Ayrton Senna lose his life in 1994?', 'CARS_RACE_IMOLA');
    ask('Which Australian circuit hosts the Bathurst 1000?', 'CARS_RACE_BATHURST');
    ask('Which English estate hosts a Festival of Speed every summer?', 'CARS_RACE_GOODWOOD');
    ask('Which California circuit has the famous "Corkscrew" corner?', 'CARS_RACE_LAGUNA_SECA');
    ask('Which endurance classic is held each year at a former airfield in Florida?', 'CARS_RACE_SEBRING');
    ask('Which rally, first held in 1911, is the oldest event on the World Rally calendar?', 'CARS_RACE_MONTE_CARLO_RALLY');
    ask('Which race became Formula 1''s first night race in 2008?', 'CARS_RACE_SINGAPORE');
    ask('Which English track, opened in 1907, was the world''s first purpose-built race circuit?', 'CARS_RACE_BROOKLANDS');
    ask('Which road race on Sicily ran from 1906 to 1977?', 'CARS_RACE_TARGA_FLORIO');
    ask('Which Italian 1,000-mile open-road race ran from 1927 to 1957?', 'CARS_RACE_MILLE_MIGLIA');
    ask('Which Texas circuit has hosted the United States Grand Prix since 2012?', 'CARS_RACE_COTA');
    ask('Which world championship includes events such as Rally Finland and Rally Sweden?', 'CARS_RACE_WRC');
    ask('Which American open-wheel series has the Indy 500 as its biggest race?', 'CARS_RACE_INDYCAR');
    ask('Which German touring car series is short for Deutsche Tourenwagen Masters?', 'CARS_RACE_DTM');
    ask('Which Mexican road race of the 1950s gave Porsche the "Carrera" name?', 'CARS_RACE_PANAMERICANA');
    ask('Which championship, governed by the FIA, is the top class of single-seater racing?', 'CARS_RACE_FORMULA_1');
    ask('Which circuit near Budapest hosted the first Formula 1 race behind the Iron Curtain in 1986?', 'CARS_RACE_HUNGARORING');
    ask('Which Belgian circuit has the famous Eau Rouge corner?', 'CAR_RACE_SPA');
    ask('Which circuit hosts the British Grand Prix?', 'CAR_RACE_SILVERSTONE');
    ask('Which circuit hosted the very first Formula 1 World Championship race in 1950?', 'CAR_RACE_SILVERSTONE');
    ask('Which Italian circuit has the Parabolica corner?', 'CAR_RACE_MONZA');
    ask('Which race is held at the speedway nicknamed "The Brickyard"?', 'CAR_RACE_INDY_500');
    ask('Which Grand Prix has the slowest corner in Formula 1, the hairpin by the Fairmont hotel?', 'CAR_RACE_MONACO');
    ask('Which race did Ford GT40s win every year from 1966 to 1969?', 'CAR_RACE_LE_MANS');
    ask('Which rally moved to South America in 2009 and to Saudi Arabia in 2020?', 'CAR_RACE_DAKAR');
    ask('Which track''s 20.8 km Nordschleife is used by carmakers to set lap records?', 'CAR_RACE_NURBURGRING');

    add_type('Car technology');
    term('CARS_TECH_ABS', 'ABS');
    term('CARS_TECH_ESC', 'Electronic stability control');
    term('CARS_TECH_CRUISE', 'Cruise control');
    term('CARS_TECH_ACC', 'Adaptive cruise control');
    term('CARS_TECH_AIRBAG', 'Airbag');
    term('CARS_TECH_REGEN', 'Regenerative braking');
    term('CARS_TECH_OVERSTEER', 'Oversteer');
    term('CARS_TECH_UNDERSTEER', 'Understeer');
    term('CARS_TECH_AQUAPLANING', 'Aquaplaning');
    term('CARS_TECH_OCTANE', 'Octane rating');
    term('CARS_TECH_DRAG', 'Drag coefficient');
    term('CARS_TECH_DOWNFORCE', 'Downforce');
    term('CARS_TECH_DRS', 'DRS');
    term('CARS_TECH_BOXER', 'Boxer engine');
    term('CARS_TECH_WANKEL', 'Wankel rotary engine');
    term('CARS_TECH_DCT', 'Dual-clutch transmission');
    term('CARS_TECH_CVT', 'CVT');
    term('CARS_TECH_PHEV', 'Plug-in hybrid');
    term('CARS_TECH_START_STOP', 'Start-stop system');
    term('CARS_TECH_HUD', 'Head-up display');
    term('CARS_TECH_POWER_STEERING', 'Power steering');
    term('CARS_TECH_LSD', 'Limited-slip differential');
    term('CARS_TECH_HORSEPOWER', 'Horsepower');
    term('CARS_TECH_TORQUE', 'Torque');
    term('CARS_TECH_AWD', 'All-wheel drive');
    term('CARS_TECH_LANE_ASSIST', 'Lane keeping assist');
    term('CARS_TECH_KERS', 'KERS');
    term('CARS_TECH_DIRECT_INJECTION', 'Direct injection');
    term('CARS_TECH_V8', 'V8');
    term('CARS_TECH_INLINE_6', 'Inline-six');
    ask('Which system stops the wheels from locking under hard braking?', 'CARS_TECH_ABS');
    ask('Which system brakes individual wheels to stop the car from skidding?', 'CARS_TECH_ESC');
    ask('Which system holds a set speed without the driver pressing the pedal?', 'CARS_TECH_CRUISE');
    ask('Which system holds a set speed and also keeps a safe distance from the car in front?', 'CARS_TECH_ACC');
    ask('Which safety device inflates in a fraction of a second during a crash?', 'CARS_TECH_AIRBAG');
    ask('What is it called when an electric motor recovers energy while the car slows down?', 'CARS_TECH_REGEN');
    ask('What is it called when the rear of the car slides out in a corner?', 'CARS_TECH_OVERSTEER');
    ask('What is it called when the front wheels lose grip and the car runs wide in a corner?', 'CARS_TECH_UNDERSTEER');
    ask('What is it called when the tyres ride on a layer of water and lose contact with the road?', 'CARS_TECH_AQUAPLANING');
    ask('Which number shows how well petrol resists engine knocking?', 'CARS_TECH_OCTANE');
    ask('Which number describes how easily a car''s shape slips through the air?', 'CARS_TECH_DRAG');
    ask('What is the aerodynamic force that pushes a car onto the track?', 'CARS_TECH_DOWNFORCE');
    ask('Which Formula 1 system opens a flap in the rear wing to help overtaking?', 'CARS_TECH_DRS');
    ask('Which engine, used by Porsche and Subaru, has horizontally opposed cylinders?', 'CARS_TECH_BOXER');
    ask('Which engine uses a triangular rotor instead of pistons?', 'CARS_TECH_WANKEL');
    ask('Which gearbox uses two clutches, one for the odd gears and one for the even ones?', 'CARS_TECH_DCT');
    ask('Which transmission has no fixed gears and uses a belt between two pulleys?', 'CARS_TECH_CVT');
    ask('Which kind of hybrid can be charged from a wall socket?', 'CARS_TECH_PHEV');
    ask('Which system switches the engine off while the car stands at the lights?', 'CARS_TECH_START_STOP');
    ask('Which display projects the speed and directions onto the windscreen?', 'CARS_TECH_HUD');
    ask('Which system helps the driver turn the steering wheel with less effort?', 'CARS_TECH_POWER_STEERING');
    ask('Which differential limits how much faster one driven wheel can spin than the other?', 'CARS_TECH_LSD');
    ask('Which unit of power was devised by James Watt?', 'CARS_TECH_HORSEPOWER');
    ask('What is the twisting force produced by an engine called?', 'CARS_TECH_TORQUE');
    ask('Which drive layout sends power to all four wheels?', 'CARS_TECH_AWD');
    ask('Which system steers the car back if it starts drifting out of its lane?', 'CARS_TECH_LANE_ASSIST');
    ask('Which energy recovery system, brought into Formula 1 in 2009, stored energy from braking?', 'CARS_TECH_KERS');
    ask('Which way of delivering fuel sprays it straight into the combustion chamber?', 'CARS_TECH_DIRECT_INJECTION');
    ask('Which engine has eight cylinders in two banks set at an angle?', 'CARS_TECH_V8');
    ask('Which engine layout, loved by BMW, has six cylinders in a single row?', 'CARS_TECH_INLINE_6');

    add_type('Car body styles');
    term('CARS_BODY_SEDAN', 'Sedan');
    term('CARS_BODY_COUPE', 'Coupe');
    term('CARS_BODY_HATCHBACK', 'Hatchback');
    term('CARS_BODY_ESTATE', 'Estate');
    term('CARS_BODY_CONVERTIBLE', 'Convertible');
    term('CARS_BODY_SUV', 'SUV');
    term('CARS_BODY_PICKUP', 'Pickup truck');
    term('CARS_BODY_MINIVAN', 'Minivan');
    term('CARS_BODY_ROADSTER', 'Roadster');
    term('CARS_BODY_LIMOUSINE', 'Limousine');
    term('CARS_BODY_SHOOTING_BRAKE', 'Shooting brake');
    term('CARS_BODY_CROSSOVER', 'Crossover');
    term('CARS_BODY_TARGA', 'Targa');
    term('CARS_BODY_FOUR_DOOR_COUPE', 'Four-door coupe');
    ask('Which body style has a rear door that includes the rear window, hinged at the roof?', 'CARS_BODY_HATCHBACK');
    ask('Which body style has two doors, a fixed roof and usually a sporty look?', 'CARS_BODY_COUPE');
    ask('Which body style has a roof that folds away?', 'CARS_BODY_CONVERTIBLE');
    ask('Which open two-seat body style is the Mazda MX-5?', 'CARS_BODY_ROADSTER');
    ask('What do the British call a station wagon?', 'CARS_BODY_ESTATE');
    ask('Which body style has four doors and a separate boot?', 'CARS_BODY_SEDAN');
    ask('Which body style has an open cargo bed behind the cab?', 'CARS_BODY_PICKUP');
    ask('Which body style, often with sliding doors, is built to carry big families?', 'CARS_BODY_MINIVAN');
    ask('Which long, chauffeur-driven body style often has a partition behind the driver?', 'CARS_BODY_LIMOUSINE');
    ask('Which body style is a sporty two-door estate, like the Ferrari FF?', 'CARS_BODY_SHOOTING_BRAKE');
    ask('Which body style puts SUV looks on a regular car platform?', 'CARS_BODY_CROSSOVER');
    ask('Which body style has a removable roof panel and a fixed roll bar, named after a Porsche?', 'CARS_BODY_TARGA');
    ask('Which body style did the 1984 Jeep Cherokee help make popular?', 'CARS_BODY_SUV');
    ask('Which body style describes the Mercedes-Benz CLS, launched in 2004?', 'CARS_BODY_FOUR_DOOR_COUPE');
END;
/execute/

-- //@UNDO
-- Removes only what this migration added: the questions it tagged with a TOPIC, the CARS_ terms,
-- and the two glossary types it created. The first migration's questions, terms and types stay.
DECLARE
    v_cat NUMBER;
BEGIN
    SELECT CAT_ID INTO v_cat FROM Q_CATEGORY WHERE NAME = 'Cars';
    DELETE FROM Q_QUESTION WHERE CAT_ID = v_cat
        AND TOPIC IN ('Car brands', 'Car countries', 'Car parts', 'Automotive people', 'Car models', 'Motorsport', 'Car technology', 'Car body styles')
        AND QUESTION_ID IN (SELECT a.QUESTION_ID FROM Q_ANSWER a JOIN Q_GLOSSARY g ON g.TERM_ID = a.TERM_ID
                            WHERE g.CAT_ID = v_cat AND g.KEY LIKE 'CAR%');
    DELETE FROM Q_GLOSSARY WHERE CAT_ID = v_cat AND KEY LIKE 'CARS\_%' ESCAPE '\';
    DELETE FROM Q_GLOSSARY_TYPE t WHERE t.NAME IN ('Car technology', 'Car body styles')
        AND NOT EXISTS (SELECT 1 FROM Q_GLOSSARY g WHERE g.TYPE_ID = t.ID);
END;
/execute/
