-- // create_quiz_invite_constraints
ALTER TABLE Q_QUIZ_INVITE
    ADD CONSTRAINT Q_QUIZ_INVITE_QUIZ_FK
        FOREIGN KEY (QUIZ_ID)
            REFERENCES Q_QUIZ(QUIZ_ID)
/execute/

ALTER TABLE Q_QUIZ_INVITE
    ADD CONSTRAINT Q_QUIZ_INVITE_USER_FK
        FOREIGN KEY (ACCOUNT_ID)
            REFERENCES Q_USER(ACCOUNT_ID)
/execute/

-- One invite per person per quiz: inviting a group twice must not double up.
ALTER TABLE Q_QUIZ_INVITE
    ADD CONSTRAINT Q_QUIZ_INVITE_UK
        UNIQUE (QUIZ_ID, ACCOUNT_ID)
/execute/

-- //@UNDO
ALTER TABLE Q_QUIZ_INVITE DROP CONSTRAINT Q_QUIZ_INVITE_QUIZ_FK
/execute/
ALTER TABLE Q_QUIZ_INVITE DROP CONSTRAINT Q_QUIZ_INVITE_USER_FK
/execute/
ALTER TABLE Q_QUIZ_INVITE DROP CONSTRAINT Q_QUIZ_INVITE_UK
/execute/
