-- // create_iq_sequences
CREATE SEQUENCE IQ_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/execute/

CREATE SEQUENCE IQ_SESSION_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/execute/

CREATE SEQUENCE IQ_RESPONSE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE
/execute/

-- //@UNDO
DROP SEQUENCE IQ_RESPONSE_SEQ
/execute/

DROP SEQUENCE IQ_SESSION_SEQ
/execute/

DROP SEQUENCE IQ_ITEM_SEQ
/execute/
