-- // create_custom_question_constraints
ALTER TABLE Q_CUSTOM_QUESTION
    ADD CONSTRAINT Q_CUSTOM_QUESTION_QUIZ_FK
        FOREIGN KEY (QUIZ_ID)
            REFERENCES Q_QUIZ(QUIZ_ID)
/execute/

ALTER TABLE Q_CUSTOM_ANSWER
    ADD CONSTRAINT Q_CUSTOM_ANSWER_QUESTION_FK
        FOREIGN KEY (QUESTION_ID)
            REFERENCES Q_CUSTOM_QUESTION(QUESTION_ID)
/execute/

-- //@UNDO
ALTER TABLE Q_CUSTOM_ANSWER DROP CONSTRAINT Q_CUSTOM_ANSWER_QUESTION_FK
/execute/
ALTER TABLE Q_CUSTOM_QUESTION DROP CONSTRAINT Q_CUSTOM_QUESTION_QUIZ_FK
/execute/
