-- // create_message_group_table
CREATE TABLE Q_MESSAGE_GROUP (
    GROUP_ID     NUMERIC(20, 0) NOT NULL,
    NAME         VARCHAR(150),
    CREATED_BY   NUMERIC(20, 0),
    UPDATED_BY   NUMERIC(20, 0),
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE
)/execute/

ALTER TABLE Q_MESSAGE_GROUP
    ADD CONSTRAINT Q_MESSAGE_GROUP_PK
        PRIMARY KEY (GROUP_ID)
/execute/

ALTER TABLE Q_USER_GROUP
    ADD CONSTRAINT USER_GROUP_MESSAGE_GROUP_FK
        FOREIGN KEY (GROUP_ID)
            REFERENCES Q_MESSAGE_GROUP(GROUP_ID)
/execute/

ALTER TABLE Q_MESSAGE
    ADD CONSTRAINT MESSAGE_MESSAGE_GROUP_FK
        FOREIGN KEY (DESTINATION)
            REFERENCES Q_MESSAGE_GROUP(GROUP_ID)
/execute/

-- //@UNDO
ALTER TABLE Q_MESSAGE DROP CONSTRAINT MESSAGE_MESSAGE_GROUP_FK
/execute/

ALTER TABLE Q_USER_GROUP DROP CONSTRAINT USER_GROUP_MESSAGE_GROUP_FK
/execute/

DROP TABLE Q_MESSAGE_GROUP
/execute/
