-- // create_quiz_invite_table
CREATE TABLE Q_QUIZ_INVITE (
    INVITE_ID NUMERIC(20, 0) NOT NULL,
    QUIZ_ID NUMERIC(20, 0) NOT NULL,
    ACCOUNT_ID NUMERIC(20, 0) NOT NULL,
    CREATED_BY NUMERIC(20, 0),
    UPDATED_BY NUMERIC(20, 0),
    CREATED_DATE DATE NOT NULL,
    UPDATED_DATE DATE
)
/execute/

ALTER TABLE Q_QUIZ_INVITE
    ADD CONSTRAINT Q_QUIZ_INVITE_PK
        PRIMARY KEY (INVITE_ID)
/execute/

-- //@UNDO
DROP TABLE Q_QUIZ_INVITE
/execute/
